// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqmunxfkbnlzfztrammd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxbXVueGZrYm5semZ6dHJhbW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzk2NDcsImV4cCI6MjA2OTY1NTY0N30.qV9zSm0Vjt_tDrt4BtYFsO1HSwOzLwoypWzFsj4cpKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});